backend:
  name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: master # Branch to update
  repo: bcvazquez/gatsby-material-starter # Repo for pushing new commits. Make sure to replace with your repo!

display_url: https://developers.planet.com
media_folder: content/images
public_folder: images
publish_mode: editorial_workflow

collections:
  - name: blog
    label: 'Post'
    folder: 'content/pages'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}.md'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Cover Image', name: 'cover', widget: 'image' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: quickstart
    label: 'Quickstart'
    description: 'Basic introductory tutorials'
    folder: 'content/quickstarts'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Thumbnail Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: tutorial
    label: 'Tutorial'
    description: 'Supa detailed tutorials'
    folder: 'content/tutorials'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Thumbnail Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
